name: Verificacion de Sintaxis Simple

on:
  # Dispara la evaluacion en cada push a la rama 'main'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el código
    - uses: actions/checkout@v4
      name: Clonar el Repositorio

    # 2. Paso de verificacion simple
    - name: Verificar Archivos
      run: |
        echo "El workflow esta configurado correctamente."
        # Puedes agregar comandos de prueba aquí, si los tienes.
